dna= input("Enter DNA sequence:")
dna= dna.strip().upper()
print("DNA counter")
print("----------")
print("cleaned dna sequence:")
print(dna)
print("-----------")
print("Sequence Length:")
print(len(dna))
